import type { PresetDefinition } from '../../presets/types'
import { FILTER_OPTIONS } from './filters/FilterStack'
import type { VirtualBuddyParams } from './types'

/**
 * Designer-facing controls. Descriptions are sparse — only where the label is
 * not self-explanatory.
 *
 * Categories (all start closed): Effects, Physics, Interaction, Scene.
 * Body scale / weight are fixed defaults (not user-facing).
 */
export const virtualBuddyPreset: PresetDefinition<VirtualBuddyParams> = {
  id: 'virtual-buddy',
  name: 'Virtual Buddy',
  tagline:
    'An articulated character under real physics. Joints, muscle tone, and gravity — the JST model as something you can push around.',

  defaults: {
    maxBuddies: 3,
    bodyScale: 1.1,
    weight: 1.5,
    model: 0,
    motion: 1,

    gravity: 9.81,
    muscleTone: 0.85,
    jointLooseness: 1,
    bounce: 0.05,
    friction: 0.8,
    airDrag: 0.05,

    grabStrength: 1,
    throwPower: 1,
    breakAwayPull: 0.35,
    fallResistance: 0.55,

    cameraDistance: 4,
    cameraHeight: 1.46,
    playDepth: 1.2,
    brightness: 1.35,
    backgroundColor: 0x1c1c1c,
    groundColor: 0x2a2a2a,
    leftLightColor: 0x00e05a,
    rimLightStrength: 1,
    showPhysicsBodies: 0,
    showAddButton: 1,

    filter: 0,
    filterStrength: 1,
    colorIntensity: 0.92,

    gbPixelSize: 5,
    gbContrast: 1.25,
    gbDither: 0.4,
    gbGrid: 0.25,
    gbColor0: 0x0f380f,
    gbColor1: 0x306230,
    gbColor2: 0x8bac0f,
    gbColor3: 0x9bbc0f,

    blEdgeThreshold: 0.15,
    blEdgeStrength: 0.45,
    blInkColor: 0x0a0a0a,
    blPosterize: 4,
    blFillBoost: 0.45,

    ps1Resolution: 256,
    ps1Affine: 0.5,
    ps1Jitter: 0.17,
    ps1ColorDepth: 4,
    ps1Dither: 0.71,
  },

  sections: [
    {
      id: 'effects',
      title: 'Effects',
      defaultOpen: false,
      controls: [
        {
          kind: 'select',
          key: 'filter',
          label: 'Style',
          options: [...FILTER_OPTIONS],
          defaultValue: 0,
        },
        {
          kind: 'slider',
          key: 'filterStrength',
          label: 'Strength',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 1,
          lowLabel: 'Subtle',
          highLabel: 'Full',
          visibleWhen: { key: 'filter', notEquals: 0 },
        },
        {
          kind: 'slider',
          key: 'colorIntensity',
          label: 'Color intensity',
          min: 0,
          max: 2,
          step: 0.01,
          defaultValue: 0.92,
          lowLabel: 'Muted',
          highLabel: 'Vivid',
          visibleWhen: { key: 'filter', notEquals: 0 },
        },
        {
          kind: 'slider',
          key: 'gbPixelSize',
          label: 'Pixel size',
          min: 1,
          max: 16,
          step: 1,
          defaultValue: 5,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'slider',
          key: 'gbContrast',
          label: 'Contrast',
          min: 0.5,
          max: 2.5,
          step: 0.01,
          defaultValue: 1.25,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'slider',
          key: 'gbDither',
          label: 'Dither',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.4,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'heading',
          key: 'heading-gb-color',
          label: 'Color',
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'color',
          key: 'gbColor0',
          label: 'Shade 1 — darkest',
          defaultValue: 0x0f380f,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'color',
          key: 'gbColor1',
          label: 'Shade 2',
          defaultValue: 0x306230,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'color',
          key: 'gbColor2',
          label: 'Shade 3',
          defaultValue: 0x8bac0f,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'color',
          key: 'gbColor3',
          label: 'Shade 4 — lightest',
          defaultValue: 0x9bbc0f,
          visibleWhen: { key: 'filter', equals: 1 },
        },
        {
          kind: 'slider',
          key: 'blEdgeStrength',
          label: 'Ink strength',
          description: 'Outline weight — thicker, heavier strokes at higher values.',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.45,
          visibleWhen: { key: 'filter', equals: 2 },
        },
        {
          kind: 'color',
          key: 'blInkColor',
          label: 'Ink color',
          defaultValue: 0x0a0a0a,
          visibleWhen: { key: 'filter', equals: 2 },
        },
        {
          kind: 'slider',
          key: 'blPosterize',
          label: 'Posterize',
          min: 2,
          max: 12,
          step: 1,
          defaultValue: 4,
          visibleWhen: { key: 'filter', equals: 2 },
        },
        {
          kind: 'slider',
          key: 'ps1Resolution',
          label: 'Virtual resolution',
          min: 60,
          max: 320,
          step: 1,
          defaultValue: 256,
          visibleWhen: { key: 'filter', equals: 3 },
        },
        {
          kind: 'slider',
          key: 'ps1Jitter',
          label: 'Jitter',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.17,
          visibleWhen: { key: 'filter', equals: 3 },
        },
        {
          kind: 'slider',
          key: 'ps1ColorDepth',
          label: 'Color depth',
          min: 2,
          max: 8,
          step: 1,
          defaultValue: 4,
          visibleWhen: { key: 'filter', equals: 3 },
        },
        {
          kind: 'slider',
          key: 'ps1Dither',
          label: 'Dither',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.71,
          visibleWhen: { key: 'filter', equals: 3 },
        },
      ],
    },
    {
      id: 'physics',
      title: 'Physics',
      defaultOpen: false,
      controls: [
        {
          kind: 'slider',
          key: 'bodyScale',
          label: 'Body scale',
          min: 0.5,
          max: 1.6,
          step: 0.05,
          defaultValue: 1.1,
          lowLabel: 'Small',
          highLabel: 'Large',
        },
        {
          kind: 'slider',
          key: 'muscleTone',
          label: 'Muscle tone',
          description: 'How firmly a performing body holds its pose.',
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.85,
          lowLabel: 'Loose',
          highLabel: 'Firm',
        },
        {
          kind: 'slider',
          key: 'gravity',
          label: 'Gravity',
          min: 0,
          max: 25,
          step: 0.1,
          defaultValue: 9.81,
          lowLabel: 'Light',
          highLabel: 'Heavy',
        },
        {
          kind: 'slider',
          key: 'fallResistance',
          label: 'Fall resistance',
          description:
            'How hard another character must bump them before they topple.',
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.55,
          lowLabel: 'Fragile',
          highLabel: 'Sturdy',
        },
      ],
    },
    {
      id: 'interaction',
      title: 'Interaction',
      defaultOpen: false,
      controls: [
        {
          kind: 'slider',
          key: 'grabStrength',
          label: 'Grab strength',
          min: 0.05,
          max: 1,
          step: 0.05,
          defaultValue: 1,
          lowLabel: 'Soft',
          highLabel: 'Firm',
        },
        {
          kind: 'slider',
          key: 'throwPower',
          label: 'Throw power',
          min: 0,
          max: 3,
          step: 0.1,
          defaultValue: 1,
          lowLabel: 'Gentle',
          highLabel: 'Hard',
        },
        {
          kind: 'slider',
          key: 'breakAwayPull',
          label: 'Break-away pull',
          description: 'Yank force before the whole body goes limp.',
          min: 0.1,
          max: 1.5,
          step: 0.05,
          defaultValue: 0.35,
          lowLabel: 'Easy',
          highLabel: 'Tough',
        },
        {
          kind: 'select',
          key: 'showAddButton',
          label: 'Add Model Button',
          options: ['None', 'Fixed', 'Focused'],
          optionDescriptions: [
            'Hides the stage add button for a clean capture frame.',
            'Keeps the add button visible in the bottom-left corner.',
            'Pops in, then hides left until you hover the bottom-left. Always on for mobile.',
          ],
          defaultValue: 1,
        },
      ],
    },
    {
      id: 'scene',
      title: 'Scene',
      defaultOpen: false,
      controls: [
        {
          kind: 'slider',
          key: 'brightness',
          label: 'Brightness',
          min: 0.3,
          max: 2.5,
          step: 0.01,
          defaultValue: 1.35,
          lowLabel: 'Dim',
          highLabel: 'Bright',
        },
        {
          kind: 'color',
          key: 'backgroundColor',
          label: 'Background',
          defaultValue: 0x1c1c1c,
        },
        {
          kind: 'color',
          key: 'groundColor',
          label: 'Ground',
          defaultValue: 0x2a2a2a,
        },
        {
          kind: 'color',
          key: 'leftLightColor',
          label: 'Rim light',
          defaultValue: 0x00e05a,
        },
        {
          kind: 'slider',
          key: 'rimLightStrength',
          label: 'Rim strength',
          min: 0,
          max: 6,
          step: 0.01,
          defaultValue: 1,
          lowLabel: 'Off',
          highLabel: 'Strong',
        },
        {
          kind: 'slider',
          key: 'cameraDistance',
          label: 'Camera distance',
          min: 2.5,
          max: 8,
          step: 0.1,
          defaultValue: 4,
          lowLabel: 'Close',
          highLabel: 'Far',
        },
        {
          kind: 'slider',
          key: 'cameraHeight',
          label: 'Camera height',
          min: 0.2,
          max: 3,
          step: 0.01,
          defaultValue: 1.46,
        },
      ],
    },
  ],
}
